"""
This type stub file was generated by pyright.
"""

import typing

__all__: list
__doc__: str
__file__: str
__name__: str
__package__: str
__test__: dict
def sort_vertices_of_regions() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

