"""
This type stub file was generated by pyright.
"""

def signed_area(ring): # -> Any:
    """Return the signed area enclosed by a ring in linear time using the
    algorithm at: https://web.archive.org/web/20080209143651/http://cgafaq.info:80/wiki/Polygon_Area
    """
    ...

def is_ccw_impl(name=...): # -> ((geometry: Unknown, **kwargs: Unknown) -> Unknown) | ((ring: Unknown) -> Any):
    """Predicate implementation"""
    ...

