"""
This type stub file was generated by pyright.
"""

import typing
import scipy.linalg._matfuncs_sqrtm as _mod_scipy_linalg__matfuncs_sqrtm

SqrtmError = _mod_scipy_linalg__matfuncs_sqrtm.SqrtmError
__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__test__: dict
def within_block_loop(R, T, start_stop_pairs, nblocks) -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

