"""
This type stub file was generated by pyright.
"""

import typing

__doc__: typing.Any
__file__: str
__name__: str
__package__: str
def binary_erosion() -> typing.Any:
    ...

def binary_erosion2() -> typing.Any:
    ...

def correlate() -> typing.Any:
    ...

def correlate1d() -> typing.Any:
    ...

def distance_transform_bf() -> typing.Any:
    ...

def distance_transform_op() -> typing.Any:
    ...

def euclidean_feature_transform() -> typing.Any:
    ...

def find_objects() -> typing.Any:
    ...

def fourier_filter() -> typing.Any:
    ...

def fourier_shift() -> typing.Any:
    ...

def generic_filter() -> typing.Any:
    ...

def generic_filter1d() -> typing.Any:
    ...

def geometric_transform() -> typing.Any:
    ...

def min_or_max_filter() -> typing.Any:
    ...

def min_or_max_filter1d() -> typing.Any:
    ...

def rank_filter() -> typing.Any:
    ...

def spline_filter1d() -> typing.Any:
    ...

def uniform_filter1d() -> typing.Any:
    ...

def watershed_ift() -> typing.Any:
    ...

def zoom_shift() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

