"""
This type stub file was generated by pyright.
"""

import typing

NeedMoreBits = ...
__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__test__: dict
def get_nonzero_line(a) -> typing.Any:
    ...

def get_read_line(a) -> typing.Any:
    ...

def get_write_line(a) -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

