"""
This type stub file was generated by pyright.
"""

__all__ = ['MAXPRINT', 'SparseEfficiencyWarning', 'SparseFormatWarning', 'SparseWarning', 'asmatrix', 'check_reshape_kwargs', 'check_shape', 'get_sum_dtype', 'isdense', 'isintlike', 'isscalarlike', 'issparse', 'isspmatrix', 'spmatrix', 'validateaxis']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

