"""
This type stub file was generated by pyright.
"""

__all__ = ['csc_matrix', 'csc_tocsr', 'expandptr', 'get_index_dtype', 'isspmatrix_csc', 'spmatrix', 'upcast']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

