"""
This type stub file was generated by pyright.
"""

__all__ = ['csr_count_blocks', 'csr_matrix', 'csr_tobsr', 'csr_tocsc', 'get_csr_submatrix', 'get_index_dtype', 'isspmatrix_csr', 'spmatrix', 'upcast']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

