"""
This type stub file was generated by pyright.
"""

__all__ = ['isscalarlike', 'matrix', 'name', 'npfunc', 'spmatrix', 'validateaxis']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

