"""
This type stub file was generated by pyright.
"""

__all__ = ['check_shape', 'dia_matrix', 'dia_matvec', 'get_index_dtype', 'get_sum_dtype', 'getdtype', 'isshape', 'isspmatrix', 'isspmatrix_dia', 'spmatrix', 'upcast_char', 'validateaxis']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

