"""
This type stub file was generated by pyright.
"""

__all__ = ['IndexMixin', 'check_shape', 'dok_matrix', 'get_index_dtype', 'getdtype', 'isdense', 'isintlike', 'isscalarlike', 'isshape', 'isspmatrix', 'isspmatrix_dok', 'itertools', 'spmatrix', 'upcast', 'upcast_scalar']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

