"""
This type stub file was generated by pyright.
"""

__all__ = ['INT_TYPES', 'IndexMixin', 'bisect_left', 'check_reshape_kwargs', 'check_shape', 'get_index_dtype', 'getdtype', 'isscalarlike', 'isshape', 'isspmatrix', 'isspmatrix_lil', 'lil_matrix', 'spmatrix', 'upcast_scalar']
def __dir__(): # -> list[str]:
    ...

def __getattr__(name): # -> Any:
    ...

