"""
This type stub file was generated by pyright.
"""

import typing
import scipy.optimize.optimize as _mod_scipy_optimize_optimize

OptimizeWarning = _mod_scipy_optimize_optimize.OptimizeWarning
__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__test__: dict
def warn(message, category, stacklevel, source) -> typing.Any:
    'Issue a warning, or maybe ignore it or raise an exception.'
    ...

def __getattr__(name) -> typing.Any:
    ...

