"""
This type stub file was generated by pyright.
"""

import typing

__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__version__: str
error = ...
def odeint(fun, y0, t, args=..., Dfun=..., col_deriv=..., ml=..., mu=..., full_output=..., rtol=..., atol=..., tcrit=..., h0=..., hmax=..., hmin=..., ixpr=..., mxstep=..., mxhnil=..., mxordn=..., mxords=...) -> typing.Any:
    '[y,{infodict,}istate] = odeint(fun, y0, t, args=(), Dfun=None, col_deriv=0, ml=, mu=, full_output=0, rtol=, atol=, tcrit=, h0=0.0, hmax=0.0, hmin=0.0, ixpr=0.0, mxstep=0.0, mxhnil=0, mxordn=0, mxords=0)\n  yprime = fun(y,t,...)'
    ...

def __getattr__(name) -> typing.Any:
    ...

