"""
This type stub file was generated by pyright.
"""

import typing

__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__pyx_capi__: dict
__test__: dict
def gaussian_kernel_estimate() -> typing.Any:
    '\n    def gaussian_kernel_estimate(points, real[:, :] values, xi, precision)\n\n    Evaluate a multivariate Gaussian kernel estimate.\n\n    Parameters\n    ----------\n    points : array_like with shape (n, d)\n        Data points to estimate from in d dimenions.\n    values : real[:, :] with shape (n, p)\n        Multivariate values associated with the data points.\n    xi : array_like with shape (m, d)\n        Coordinates to evaluate the estimate at in d dimensions.\n    precision : array_like with shape (d, d)\n        Precision matrix for the Gaussian kernel.\n\n    Returns\n    -------\n    estimate : double[:, :] with shape (m, p)\n        Multivariate Gaussian kernel estimate evaluated at the input coordinates.\n    '
    ...

def geninvgauss_logpdf() -> typing.Any:
    ...

def von_mises_cdf() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

