"""
This type stub file was generated by pyright.
"""

import typing

__doc__: str
__file__: str
__name__: str
__package__: str
__test__: dict
def group_dense() -> typing.Any:
    ...

def group_sparse() -> typing.Any:
    ...

def __getattr__(name) -> typing.Any:
    ...

