"""
This type stub file was generated by pyright.
"""

import typing
import scipy._lib._ccallback as _mod_scipy__lib__ccallback

LowLevelCallable = _mod_scipy__lib__ccallback.LowLevelCallable
__doc__: typing.Any
__file__: str
__name__: str
__package__: str
__pyx_capi__: dict
__test__: dict
nan: float
def __getattr__(name) -> typing.Any:
    ...

