"""
This type stub file was generated by pyright.
"""

from .lib import GEOSException, Geometry, geos_capi_version, geos_capi_version_string, geos_version, geos_version_string
from .errors import setup_signal_checks
from ._geometry import *
from .creation import *
from .constructive import *
from .predicates import *
from .measurement import *
from .set_operations import *
from .linear import *
from .coordinates import *
from .strtree import *
from .io import *
from shapely.geometry import GeometryCollection, LineString, LinearRing, MultiLineString, MultiPoint, MultiPolygon, Point, Polygon
from . import _version

__version__ = _version.get_versions()["version"]
