"""
This type stub file was generated by pyright.
"""

"""Coordinate sequence utilities
"""
class CoordinateSequence:
    """
    Iterative access to coordinate tuples from the parent geometry's coordinate
    sequence.

    Example:

      >>> from shapely.wkt import loads
      >>> g = loads('POINT (0.0 0.0)')
      >>> list(g.coords)
      [(0.0, 0.0)]

    """
    def __init__(self, coords) -> None:
        ...
    
    def __len__(self):
        ...
    
    def __iter__(self): # -> Generator[tuple[Unknown, ...], None, None]:
        ...
    
    def __getitem__(self, key): # -> tuple[Unknown, ...] | list[Unknown]:
        ...
    
    def __array__(self, dtype=...): # -> Unknown:
        ...
    
    @property
    def xy(self): # -> tuple[array[float], array[float]]:
        """X and Y arrays"""
        ...
    


