"""
This type stub file was generated by pyright.
"""

from ._basic import _dispatch

'''Multimethods for fast Hankel transforms.
'''
__all__ = ['fht', 'ifht']
@_dispatch
def fht(a, dln, mu, offset=..., bias=...): # -> tuple[Dispatchable]:
    """fht multimethod."""
    ...

@_dispatch
def ifht(A, dln, mu, offset=..., bias=...): # -> tuple[Dispatchable]:
    """ifht multimethod."""
    ...

